### ISSUE TITLE
Data not showing up

### ISSUE THREAD

**Issue by umairahmed17** [umairahmed17/ACF-Group-Field-Elementor-Tag#1]
> > > I also ran into the same issue so I modified the elementor acf tag to allow for groups. It works for nested groups as well. [Link to my gist](https://gist.github.com/umairahmed17/f1cfeea10e40cb8ef4057d3a99ccd0b3)
> > 
> > 
> > Awesome @umairahmed17 ! Could you let us know where to add that file/code to apply your patch?
> 
> I have created a plugin just for ease here is the link [Plugin Link](https://github.com/umairahmed17/ACF-Group-Field-Elementor-Tag). I am using it on my live site. Let me know if this works for you.

Thanks for the link.
I can see the group sub fields now under Group Fields/taxoname/sub field name in Elementor, but it doesn't pull the data I entered from them in a loop. This may be an error on my end or it just doesn't work for me.
Any ideas?

_Originally posted by @Const4ntFlux in https://github.com/elementor/elementor/issues/9571#issuecomment-1174037227_

**Comment by umairahmed17** [comment]
@Const4ntFlux I have updated the repo. Now fields are showing up.

**Comment by bgrrota** [comment]
@umairahmed17 I am using it to show some theme settings of a group from ACF but data in the frontend doesn't show up for me now!

**Comment by bgrrota** [comment]
@umairahmed17 actually it's working but the $field['value'] is returning empty on the render!
