### ISSUE TITLE
Data not visible when there are multiple child groups except the first one

### ISSUE THREAD

**Issue by keerthi-n** [umairahmed17/ACF-Group-Field-Elementor-Tag#11]
I am having a field group with parent element as group, and has multiple child groups. In elementor dynamic fields, ACF group fields are visible in the dropdown to select. But after selecting, the values are shown only from the first child group. from second and onwards, nothing is coming in the webpage. 

Kindly help here.

**Comment by umairahmed17** [comment]
Fixed after #12 .
