### ISSUE TITLE
ACF Pro 6.2, Elementor Pro 3.15 - ACF Groups not visible

### ISSUE THREAD

**Issue by PistonPL** [umairahmed17/ACF-Group-Field-Elementor-Tag#7]
Plugin just stopped working with new ACF and/or Elementor (hard for me to say which one is the cause).

**Comment by pixelwisestudio** [comment]
I just checked and by my side it's working. I have ACF Pro 2.0 and Elementor 3.15.2!!

**Comment by paburmester** [comment]
It's not working anymore for me too :( Im using Elementor Pro 3.15.1 and ACF Pro 6.2.0, I can see the Group Fields on my backend, but once I select one this doesnt show any value.

**Comment by umairahmed17** [comment]
Hi Nobert,

Thank you for pointing that out. I stopped maintaining the plugin a long
time ago as it has become very difficult for me to take out time but I will
try to take a look at it as soon as I can.

**Comment by pixelwisestudio** [comment]
tbh I'm willing to pay for your time and your work

**Comment by paburmester** [comment]
Let me know if I can do it too, this plugin is very helpful!
